
model_config:
  quant8: False
  quant4: False
  token: ${HF_TOKEN}
  peft: False

data_config:
  task_type: cls_toxic
  prefix: 'токсичный текст: '
  collator_type: simple
  max_target_len: 5
  max_input_len: 1024
  per_device_inference_batch_size: 20

quant_config:
  zero_point: True
  q_group_size: 128
  w_bit: 4
  version: GEMM